### PR TITLE
Add `domain_hash`

### PR DESCRIPTION
**Pull request by polytypic**
This PR adds a `domain_hash ()` helper that computes a hash of `Domain.self ()` suitable e.g. for use as a basis for indexing into an array to avoid contention in multicore algorithms and data structures.

### CODE REVIEW

**Comment by lyrm** [comment]
I can see the case of use, but I don't get how to use it. Is the `hash` meant to be used directly as an index ? If so, how to determine the size of the array, not knowing which hash values other domains are going to have ?

**Comment by polytypic** [comment]
> I can see the case of use, but I don't get how to use it. Is the `hash` meant to be used directly as an index ? If so, how to determine the size of the array, not knowing which hash values other domains are going to have ?

Yes, the idea is/was that you choose the array size according to the level of parallelism you want to achieve.  For example, to be able to run 4 operations in parallel, you will need an array of at least 4 elements assuming operations on different elements of the array can proceed in parallel without interference.

Alas, I've come to the conclusion that a hash (or random value) is not the right approach.

The problem is that a hash is not good enough.  While an array of `n` elements would allow `n` operation to run in parallel, due to the [birthday paradox](https://en.wikipedia.org/wiki/Birthday_problem), to really scale reliably enough to a desired level of parallelism using hash values, you'd need roughly about twice as many bits for the index.  For example, to reliably (enough) to scale to allow 4 parallel operations you'd need roughly an array of 16 elements.  For 16 parallel operations you need an array of 256 elements.  And so on.  That quickly becomes impractical.

Note that with ordinary uses of hashing things are typically quite different.  You typically have a large number of keys (easily thousands or possibly even many orders of magnitude more) and some percentage of hash collisions is just fine.  With CPU cores, however, you typically don't have that many.  You might have only 4 or 8 cores, for example.  Hash collisions will then be a big problem.  You might only get 2 or 3 parallel operations with 4 cores.  That is embarrassing.

So, what we actually need is something better that more reliably allows `n`-way parallelism with an array of size `n`.

An idea I've been playing with is to introduce a concept of a "domain index" and likely make it a "temporary domain index", which is only guaranteed to be unique at a point in time.  Each time you ask for a "temporary domain index" then you are guaranteed to get an index that is unique among the currently live domains, but on a subsequent call (on the same domain) to get a "temporary domain index" again, you might get a different index (with otherwise the same guarantees).  The indices would be allocated dynamically such that each domain gets a unique index and that the indices are packed densely &mdash; ideally such that if you have `n` live domains then their indices would be between `0` and `n-1` (and using an array of size `n` you would be guaranteed no collisions).   When domains die and holes are left in the range, the indices of domains outside the optimal range would be reallocated to keep the indices packed tightly.

Perhaps something more sophisticated could also be devised.  For example, you might have a data structure that is only used by a subset of domains/cores.  In such a case you might want to use an array with an element only for each domain actually using the data structure (not for all domains).  If the domain indices would be allocated over the whole range of domains, you might still get collisions.

**Comment by lyrm** [comment]
Thanks !

**Comment by polytypic** [comment]
I'm closing this as the approach of using an "instantaneous domain index" (#10) seems preferable.

**Pull request closed without merging**
